
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 25 20:05:14 CEST 2018
//----------------------------------------------------

package use_case_diagram;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int C_BRACE = 10;
  public static final int T_ASSOCIATION = 5;
  public static final int EOF = 0;
  public static final int O_BRACE = 9;
  public static final int T_USECASE = 4;
  public static final int error = 1;
  public static final int T_ACTOR = 3;
  public static final int T_INCLUDE = 6;
  public static final int T_EXTEND = 7;
  public static final int NAME = 8;
  public static final int T_MODEL = 2;
}

